### ISSUE TITLE
No link for the website

### ISSUE THREAD

**Issue by Karyum** [WebAhead7/egestas#1]
the website needs to be deployed 🚀  so anyone can easily view it online, this these week's projects we use Github pages to deploy them ([here is part of the video on how to do it](https://youtu.be/8hrJ4oN1u_8?t=350)).

**having an index.html in the project is important in Github pages** since it is the root file for the deployment

**Comment by Karyum** [comment]
although now thinking about it,  I remember @mjmajadly deploying the website yesterday, if so add it to the about section of the repository or in the README

**Comment by mjmajadly** [comment]
Link added to readme

Thanks,
MJ
Salah Majadly

**Comment by Karyum** [comment]
amazing 👍
