### ISSUE TITLE
 Note...

### ISSUE THREAD

**Issue by shoogkabiya** [WebAhead7/egestas#3]
Everything is good but lacks information for the company....

**Comment by nuwrss** [comment]
Hi @shoogkabiya ,
Thank you for your notice , we will add the information for our company .

**Comment by mjmajadly** [comment]
our website has lots of information in "about us."
in the front page/home page, it says the first line "Luxury Rentals Everywhere Anywhere", and in the middle it says "What do you want to rent ?!"
We are luxury rental agency :)
