### ISSUE TITLE
Code Structure 

### ISSUE THREAD

**Issue by ghost** [WebAhead7/egestas#5]
Good morning,
You have a very clear organized code, I managed to understand every thing.
Just one little advice that may help you even get more organized if you decided to scale up your project and that is to split your files into folders. For instance your entry page to be in main folder, move images to new folder and all other code in another new folder that you may call it src. 
And I suggest to use name conventions to the folders and also for files, again these little advises may save you time if you decided to scale your project. 
Good luck!
**Asra3sala7ef** team.

**Comment by nuwrss** [comment]
Hi @nizarhalloun ,
Thank you for your notice , we will work to make our code more organized .

**Comment by nuwrss** [comment]
Done .
