### ISSUE TITLE
Design and links

### ISSUE THREAD

**Issue by muhkham** [WebAhead7/egestas#6]
Nice design,  you get  impressed in the home page, you put a nice info about your agency and members.
I liked the members photos at the end. 

there is no need to homepage button, you could add a button in every section in about us to get you back to the top of the page.
I prefer to link the video in the homepage pic to the button and not to the photo.

overall, you did a really good job guys. go on 👍

**Comment by nuwrss** [comment]
Hi @muhkham  , 
thank you , we will work on your notice .

**Comment by nuwrss** [comment]
Done .
