### ISSUE TITLE
Great work! 

### ISSUE THREAD

**Issue by halaassaly** [WebAhead7/egestas#7]
The website is well organized, the design and colors you guys choose matches and suites the topic. I liked that you added comments in the code so that everyone would understand the code. just Great gob! I think maybe you could add a little more info about the agency in the index page (home page) so that the user would understand what are the services you offer.
in addition, it is not clear what icons can be pressed in the home page, maybe add more functions that indicates items that can be pressed ( exp, photos get bigger when mouse get over).

**Comment by nuwrss** [comment]
Hi @halaassaly  
Thank you for the compliment .
About the icons on the homepage these is not a buttons but they are a special services that make our business unique 
and offer the customer a special needs that cant get in another company .
